### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Grufoony** [slicedlime/seasons#7]
I've tried the datapack on my vanilla server, versione 1.19.3, using a client with optifine (pre-release version).
It was winter and wen i right-clicked on an unemployed villager the game crashed.
I don't actually know if it's a problem from optifine or datapack itself.
In case, here is the crash report, hope it helps.
NOTE: Only the client crashed, the server remained online.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-03-03 22:41:05
Description: Getting block state

dbe: Missing Palette entry for index 1.
	at day.a(SourceFile:64)
	at dbh.a(SourceFile:157)
	at dbh.a(SourceFile:151)
	at dbb.a(LevelChunkSection.java:52)
	at dba.a_(SourceFile:184)
	at net.optifine.override.ChunkCacheOF.loadBlockStates(ChunkCacheOF.java:175)
	at net.optifine.override.ChunkCacheOF.renderStart(ChunkCacheOF.java:148)
	at fgl$c$b.a(ChunkRenderDispatcher.java:973)
	at fgl$c$b.a(ChunkRenderDispatcher.java:909)
	at fgl.lambda$runTask$0(ChunkRenderDispatcher.java:196)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at day.a(SourceFile:64)
	at dbh.a(SourceFile:157)
	at dbh.a(SourceFile:151)
	at dbb.a(LevelChunkSection.java:52)
	at dba.a_(SourceFile:184)

-- Block being got --
Details:
	Location: World: (-273,96,346), Section: (at 15,0,10 in -18,6,21; chunk contains blocks -288,-64,336 to -273,319,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at dba.a_(SourceFile:184)
	at net.optifine.override.ChunkCacheOF.loadBlockStates(ChunkCacheOF.java:175)
	at net.optifine.override.ChunkCacheOF.renderStart(ChunkCacheOF.java:148)
	at fgl$c$b.a(ChunkRenderDispatcher.java:973)
	at fgl$c$b.a(ChunkRenderDispatcher.java:909)
	at fgl.lambda$runTask$0(ChunkRenderDispatcher.java:196)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [fcz['CecchinoG24'/129, l='ClientLevel', x=-272.77, y=98.00, z=355.33]]
	Chunk stats: 3025, 690
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,135,0), Section: (at 0,7,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6449311 game time, 10636530 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at eyz.a(ClientLevel.java:583)
	at ejf.d(SourceFile:2390)
	at ejf.f(SourceFile:874)
	at ejf.e(SourceFile:770)
	at net.minecraft.client.main.Main.a(SourceFile:244)
	at net.minecraft.client.main.Main.main(SourceFile:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 847503440 bytes (808 MiB) / 3019898880 bytes (2880 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20691.72
	Virtual memory used (MB): 18530.65
	Swap memory total (MB): 4393.06
	Swap memory used (MB): 264.19
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.3-OptiFine_HD_U_I2_pre5
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.18, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.19.3_HD_U_I2_pre5
	OptiFine Build: 20230219-203817
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 4
	Antialiasing: 0
	Multitexture: true
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 531.18
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by slicedlime** [comment]
This is an optifine crash - you'll have to report that to them.
